# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
# Change $SCRIPT_DIR to the location of your scripts!
command=$SCRIPT_DIR/$BLOCK_NAME
separator_block_width=15
markup=pango


[spotify]
command=playerctl metadata --format "Now playing: {{ artist }} - {{ album }} - {{ title }}"
label=   
interval=10
color=#81b71a




[volume-pipewire]
command=$SCRIPT_DIR/volume-pipewire/volume-pipewire
interval=1
signal=1
#MIXER=[determined automatically]
#SCONTROL=[determined automatically]
##exposed format variables: ${SYMB}, ${VOL}, ${INDEX}, ${NAME}
#LONG_FORMAT="${SYMB} ${VOL}% [${INDEX}:${NAME}]"
#SHORT_FORMAT="${SYMB} ${VOL}% [${INDEX}]"
AUDIO_HIGH_SYMBOL=   
AUDIO_MED_THRESH=50
AUDIO_MED_SYMBOL=  
AUDIO_LOW_THRESH=0
AUDIO_LOW_SYMBOL= 
#AUDIO_DELTA=5
#DEFAULT_COLOR="#ffffff"
#MUTED_COLOR="#a0a0a0"
#USE_ALSA_NAME=0
#USE_DESCRIPTION=0
## SUBSCRIBE=1 requires interval=persist and always uses LONG_FORMAT
#SUBSCRIBE=0

[temperature]
command=$SCRIPT_DIR/temperature/temperature
label=  
interval=10
#T_WARN=70
#T_CRIT=90
#SENSOR_CHIP=""
#

[cpu_usage]
command=$SCRIPT_DIR/cpu_usage/cpu_usage
interval=2
LABEL=CPU 
#min_width=CPU: 100.00%
#T_WARN=50
#T_CRIT=80
#DECIMALS=2
#COLOR_NORMAL=#EBDBB2
#COLOR_WARN=#FFFC00
#COLOR_CRIT=#FF0000
#

[memory]
command=$SCRIPT_DIR/memory/memory
label=󰍛   
interval=30

# Date Time
#
[time]
command=date '+%d-%m %H:%M'
interval=5

# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
#[keyindicator]
#KEY=CAPS
#markup=pango
#interval=once
#signal=11

#[keyindicator]
#KEY=NUM
#markup=pango
#interval=once
#signal=11
[simple-2]
full_text=: :
color=#717171
