# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
# Change $SCRIPT_DIR to the location of your scripts!
command=$SCRIPT_DIR/$BLOCK_NAME
separator_block_width=15
markup=pango
color=#999999

[spotify]
command=playerctl metadata --format "{{ artist }} - {{ title }}"
label=   
interval=10
color=#81b71a

#[spotifyp]
#full_text=󰒮
#command=playerctl --player=spotify previous 

[clickme]
full_text=󰐎
command=playerctl play-pause

#[clickme]
#full_text=󰒭
#command=playerctl --player=spotify next 


[volume-pipewire]
command=$SCRIPT_DIR/volume-pipewire/volume-pipewire
interval=1
signal=1
#MIXER=[determined automatically]
#SCONTROL=[determined automatically]
##exposed format variables: ${SYMB}, ${VOL}, ${INDEX}, ${NAME}
LONG_FORMAT="${SYMB}${VOL}%"
SHORT_FORMAT="${SYMB} ${VOL}%"
AUDIO_HIGH_SYMBOL=   
AUDIO_MED_THRESH=50
AUDIO_MED_SYMBOL=  
AUDIO_LOW_THRESH=0
AUDIO_LOW_SYMBOL= 
#AUDIO_DELTA=5
DEFAULT_COLOR="999999"
#MUTED_COLOR="#a0a0a0"
#USE_ALSA_NAME=0
#USE_DESCRIPTION=0
## SUBSCRIBE=1 requires interval=persist and always uses LONG_FORMAT
#SUBSCRIBE=0


[temperature]
command=$SCRIPT_DIR/temperature/temperature
label= 
interval=10
T_WARN=70
T_CRIT=90
#SENSOR_CHIP=""
#

[cpu_usage]
command=$SCRIPT_DIR/cpu_usage/cpu_usage
interval=2
LABEL=  
#min_width=CPU: 100.00%
#T_WARN=50
#T_CRIT=80
#DECIMALS=2
#COLOR_NORMAL=#EBDBB2
#COLOR_WARN=#FFFC00
#COLOR_CRIT=#FF0000
#
[monitors]
command=$SCRIPT_DIR/monitor_manager/monitor_manager
interval=once
SHOW_ON_OFF=1
SHOW_NAMES=1
SHOW_PRIMARY=1
SHOW_MODE=1
#SHOW_BLANKED=1
SHOW_DUPLICATE=1
SHOW_ROTATION=1
SHOW_REFLECTION=1
SHOW_BRIGHTNESS=1
SHOW_BRIGHTNESS_VALUE=0
SHOW_UP_DOWN=1
FONT_FAMILY=JetBrains Mono Nerd Font
FONT_SIZE=10
#CLOSE_TO_BOUNDARY_BUFFER=20


[memory]
command=$SCRIPT_DIR/memory/memory
label=󰍛 
interval=30

[eyedropper]
command=$SCRIPT_DIR/eyedropper/eyedropper
full_text= 
instance=#999999
markup=pango
CLIPBOARD=true
#SWAY=true

[battery2]
command=$SCRIPT_DIR/battery2/battery2
markup=pango
interval=30


# Date Time
#
[time]
command=date '+%d-%m %H:%M'
interval=5


# Key indicators
#
# Add the following bindings to i3 config file:
#
# bindsym --release Caps_Lock exec pkill -SIGRTMIN+11 i3blocks
# bindsym --release Num_Lock  exec pkill -SIGRTMIN+11 i3blocks
#[keyindicator]
#KEY=CAPS
#markup=pango
#interval=once
#signal=11

#[keyindicator]
#KEY=NUM
#markup=pango
#interval=once
#signal=11
