#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.screenlayout/display.sh

bspc monitor eDP-1  -d I
bspc monitor HDMI-1-0  -d II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/scripts/wallpaper.sh &
polybar -c ~/.config/polybar/forest/config.ini &
polybar -c ~/.config/polybar/forest/config2.ini &
dropbox &
picom --backend xrender &
redshift -l -22.1175:-45.0517

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer false
